[project]
name = "AnnonChat"
version = "0.1.0"
description = "Chat temporário para troca de mensagens e anexos de forma segura."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "flask-socketio>=5.5.1",
    "gunicorn>=23.0.0",
]
